{{ if  .Values.tls.certManager.enabled }}
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: {{ .Values.domain }}-issuer
spec:
  acme:
    server: {{ .Values.tls.certManager.acme.server }}
    email: {{ .Values.tls.certManager.acme.email }}
    privateKeySecretRef:
      name: {{ .Values.domain }}-acme-tls-secret
    solvers:
      {{- if hasKey .Values.tls.certManager "dns01" }}
      - dns01:
          {{- if .Values.tls.certManager.dns01.route53 }}
          route53:
            region: {{ .Values.tls.certManager.dns01.route53.region }}
            accessKeyID: {{ .Values.tls.certManager.dns01.route53.accessKeyID }}
            hostedZoneID: {{ .Values.tls.certManager.dns01.route53.hostedZoneID }}
            secretAccessKeySecretRef:
              name: aws-secret
              key: AWS_SECRET_ACCESS_KEY
          {{- else }}
          clouddns:
            project: {{ .Values.tls.certManager.dns01.clouddns.project }}
            serviceAccountSecretRef:
              name: {{ .Values.tls.certManager.dns01.clouddns.serviceAccountSecretRef.name }}
              key: {{ .Values.tls.certManager.dns01.clouddns.serviceAccountSecretRef.key }}  
          {{- end }}
      {{- else }}
      - http01: {}
      {{- end }}
{{ end }}
