apiVersion: sci-toolkit.konstellation.io/v1alpha1
kind: UserTools
metadata:
  name: gustavo
spec:
  # Default values copied from <project_dir>/helm-charts/usertools/values.yaml
  
  # Default values for usertools.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.

  domain: toolkit.local
  username: gustavo

  storage:
    size: 10Gi
    className: standard

  sharedVolume:
    name: ""

  tls:
    enabled: false
