apiVersion: sci-toolkit.konstellation.io/v1alpha1
kind: UserTools
metadata:
  name: john-doe
spec:
  # Default values copied from <project_dir>/helm-charts/usertools/values.yaml
  
  # Default values for usertools.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.

  domain: toolkit.local
  kdl:
    enabled: false
  ingress:
    type: "nginx"
  username: john-doe

  storage:
    size: 10Gi
    className: standar

  sharedVolume:
    name: ""

  tls: false
  giteaOauth2Ssetup:
    image:
      repository: terminus7/gitea-oauth2-setup
      tag: latest
      pullPolicy: IfNotPresent
  jupyter:
    image:
      repository: terminus7/jupyterlab-gpu
      tag: latest
      pullPolicy: IfNotPresent
  repoCloner:
    image:
      repository: konstellation/user-repo-cloner
      tag: latest
      pullPolicy: IfNotPresent
  vscode:
    image:
      repository: terminus7/sci-toolkit-vscode
      tag: latest
      pullPolicy: IfNotPresent
