apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: usertools.sci-toolkit.konstellation.io
spec:
  group: sci-toolkit.konstellation.io
  names:
    kind: UserTools
    listKind: UserToolsList
    plural: usertools
    singular: usertools
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1alpha1
    served: true
    storage: true
