apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-tools-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: user-tools-operator
  template:
    metadata:
      labels:
        name: user-tools-operator
    spec:
      serviceAccountName: user-tools-operator
      containers:
        - name: user-tools-operator
          # Replace this with the built image name
          image: terminus7/sci-toolkit-user-tools-operator:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "user-tools-operator"
