{{ if not .Values.kdl.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: drone-runner
  name: drone-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      run: drone-runner
  template:
    metadata:
      labels:
        run: drone-runner
    spec:
      serviceAccountName: drone-runner
      containers:
      - name: secrets
        image: drone/kubernetes-secrets:latest
        ports:
        - containerPort: 3000
        env:
        - name: SECRET_KEY
          value: {{ .Values.drone.pluginSecret }}
        - name:   KUBERNETES_NAMESPACE
          value: {{ .Release.Namespace }}
      - image: {{ .Values.droneRunner.image.repository }}:{{ .Values.droneRunner.image.tag }}
        name: drone-runner
        envFrom:
          - configMapRef:
              name: drone-config
      {{- if .Values.kdl.local }}
        volumeMounts:
        - mountPath: /etc/ssl/certs/mkcert-ca.pem
          name: mkcert-ca
          subPath: mkcert-ca.crt
      volumes:
      - name: mkcert-ca
        secret:
          secretName: mkcert-ca
      {{- end }}
{{ end }}