
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-03-10T12:37:39-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "935c118a1c98f4f79c2c7a516daeffa7ea1b5d6c",
 "version": "1.0.0b3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
