apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-tools.fullname" . }}-code
  labels:
{{ include "user-tools.labels" . | indent 4 }}
spec:
  clusterIP: None
  ports:
    - port: 80
      targetPort: 4180
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "user-tools.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
