{{ if not .Values.kdl.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mlflow-oauth2-secrets
type: Opaque
data:
  DEPLOYMENT_SECRET_NAME: {{ print "mlflow-oauth2-credentials" | b64enc }}
  GITEA_REDIRECT_URIS: {{ printf "%s://mlflow.%s/oauth2/callback" ( include "protocol" . ) .Values.domain | b64enc }}
  GITEA_APPLICATION_NAME: {{ print "mlflow" | b64enc }}
{{ end }}
