release-mlflow-image:
  stage: semantic-release
  image: node:10
  before_script:
    - npm install --prefix mlflow
  script:
    - cd mlflow && npx semantic-release -e semantic-release-monorepo
  only:
    changes:
      - mlflow/**/*
    refs:
      - master

publish_mlflow_docker_image:
  stage: publish
  image: docker:latest
  services:
    - docker:dind
  variables:
    IMAGE_PROJECT_NAME: "terminus7/mlflow"
    README_FILEPATH: "./mlflow/README.md"
  before_script:
    - apk add bash git coreutils --update
    - TAG=${CI_COMMIT_TAG#"mlflow-v"}
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
  script:
    - docker build -t $IMAGE_PROJECT_NAME:$TAG ./mlflow
    - docker tag $IMAGE_PROJECT_NAME:$TAG $IMAGE_PROJECT_NAME:latest
    - docker push $IMAGE_PROJECT_NAME:$TAG
    - docker push $IMAGE_PROJECT_NAME:latest
    - ./scripts/update-dockerhub-readme.sh
  after_script:
    - docker rmi $IMAGE_PROJECT_NAME:$TAG
  only:
    - /^mlflow-v\d*.\d*.\d*$/
  when: manual
