
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-09-26T13:20:26-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "8f358d6e0f06a2f7a88b2dece75fda52fef75f40",
 "version": "5.0.0a5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
