{{ if not .Values.kdl.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app:  postgres-config
data:
  POSTGRES_DB: {{ .Values.postgres.dbName }}
  POSTGRES_PASSWORD: {{ .Values.postgres.dbPassword }}
{{ end }}
