{{ if not .Values.kdl.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initdb
  labels:
    app: postgres-initdb
data:
  init.sql: |
    CREATE DATABASE hub ;
    CREATE DATABASE drone ;
{{ end }}
