apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-config
  labels:
    app:  minio-config
data:
  config.json: |-
    {
      "version": "9",
      "hosts": {
        "minio": {
          "url": "http://{{ .Release.Name }}-minio:9000",
          "accessKey": "{{ .Values.minio.accessKey }}",
          "secretKey": "{{ .Values.minio.secretKey }}",
          "api": "S3v4",
          "lookup": "auto"
        }
      }
    }
