{{ if not .Values.kdl.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: gitea-admin-secrets
type: Opaque
data:
  GITEA_ADMIN_USER: {{ .Values.gitea.admin.username | b64enc }}
  GITEA_ADMIN_PASSWORD: {{ .Values.gitea.admin.password | b64enc }}
{{ end }}
