{{ if not .Values.kdl.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: tools-secret
  labels:
    app:  tools-secret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.minio.accessKey | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.minio.secretKey | b64enc }}
  MINIO_URL: {{ printf "http://%s-minio:9000" .Release.Name | b64enc }}
  MLFLOW_URL: {{ printf "http://%s:5000" .Values.mlflow.name | b64enc }}
  MLFLOW_S3_ENDPOINT_URL: {{ printf "http://%s-minio:9000" .Release.Name | b64enc }}
{{ end }}
